global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'cinematcha-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:3001']
